# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wts/CVIA_trt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wts/CVIA_trt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wts/CVIA_trt/CMakeFiles /home/wts/CVIA_trt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wts/CVIA_trt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trt

# Build rule for target.
trt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trt
.PHONY : trt

# fast build rule for target.
trt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/build
.PHONY : trt/fast

src/TensorRT/calibrator/calibrator.o: src/TensorRT/calibrator/calibrator.cpp.o
.PHONY : src/TensorRT/calibrator/calibrator.o

# target to build an object file
src/TensorRT/calibrator/calibrator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/calibrator/calibrator.cpp.o
.PHONY : src/TensorRT/calibrator/calibrator.cpp.o

src/TensorRT/calibrator/calibrator.i: src/TensorRT/calibrator/calibrator.cpp.i
.PHONY : src/TensorRT/calibrator/calibrator.i

# target to preprocess a source file
src/TensorRT/calibrator/calibrator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/calibrator/calibrator.cpp.i
.PHONY : src/TensorRT/calibrator/calibrator.cpp.i

src/TensorRT/calibrator/calibrator.s: src/TensorRT/calibrator/calibrator.cpp.s
.PHONY : src/TensorRT/calibrator/calibrator.s

# target to generate assembly for a file
src/TensorRT/calibrator/calibrator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/calibrator/calibrator.cpp.s
.PHONY : src/TensorRT/calibrator/calibrator.cpp.s

src/TensorRT/logger/logger.o: src/TensorRT/logger/logger.cpp.o
.PHONY : src/TensorRT/logger/logger.o

# target to build an object file
src/TensorRT/logger/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/logger/logger.cpp.o
.PHONY : src/TensorRT/logger/logger.cpp.o

src/TensorRT/logger/logger.i: src/TensorRT/logger/logger.cpp.i
.PHONY : src/TensorRT/logger/logger.i

# target to preprocess a source file
src/TensorRT/logger/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/logger/logger.cpp.i
.PHONY : src/TensorRT/logger/logger.cpp.i

src/TensorRT/logger/logger.s: src/TensorRT/logger/logger.cpp.s
.PHONY : src/TensorRT/logger/logger.s

# target to generate assembly for a file
src/TensorRT/logger/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/logger/logger.cpp.s
.PHONY : src/TensorRT/logger/logger.cpp.s

src/TensorRT/model/model.o: src/TensorRT/model/model.cpp.o
.PHONY : src/TensorRT/model/model.o

# target to build an object file
src/TensorRT/model/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/model/model.cpp.o
.PHONY : src/TensorRT/model/model.cpp.o

src/TensorRT/model/model.i: src/TensorRT/model/model.cpp.i
.PHONY : src/TensorRT/model/model.i

# target to preprocess a source file
src/TensorRT/model/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/model/model.cpp.i
.PHONY : src/TensorRT/model/model.cpp.i

src/TensorRT/model/model.s: src/TensorRT/model/model.cpp.s
.PHONY : src/TensorRT/model/model.s

# target to generate assembly for a file
src/TensorRT/model/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/model/model.cpp.s
.PHONY : src/TensorRT/model/model.cpp.s

src/TensorRT/utils/utils.o: src/TensorRT/utils/utils.cpp.o
.PHONY : src/TensorRT/utils/utils.o

# target to build an object file
src/TensorRT/utils/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/utils/utils.cpp.o
.PHONY : src/TensorRT/utils/utils.cpp.o

src/TensorRT/utils/utils.i: src/TensorRT/utils/utils.cpp.i
.PHONY : src/TensorRT/utils/utils.i

# target to preprocess a source file
src/TensorRT/utils/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/utils/utils.cpp.i
.PHONY : src/TensorRT/utils/utils.cpp.i

src/TensorRT/utils/utils.s: src/TensorRT/utils/utils.cpp.s
.PHONY : src/TensorRT/utils/utils.s

# target to generate assembly for a file
src/TensorRT/utils/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/TensorRT/utils/utils.cpp.s
.PHONY : src/TensorRT/utils/utils.cpp.s

src/ZEDX/ZEDX.o: src/ZEDX/ZEDX.cpp.o
.PHONY : src/ZEDX/ZEDX.o

# target to build an object file
src/ZEDX/ZEDX.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/ZEDX/ZEDX.cpp.o
.PHONY : src/ZEDX/ZEDX.cpp.o

src/ZEDX/ZEDX.i: src/ZEDX/ZEDX.cpp.i
.PHONY : src/ZEDX/ZEDX.i

# target to preprocess a source file
src/ZEDX/ZEDX.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/ZEDX/ZEDX.cpp.i
.PHONY : src/ZEDX/ZEDX.cpp.i

src/ZEDX/ZEDX.s: src/ZEDX/ZEDX.cpp.s
.PHONY : src/ZEDX/ZEDX.s

# target to generate assembly for a file
src/ZEDX/ZEDX.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/ZEDX/ZEDX.cpp.s
.PHONY : src/ZEDX/ZEDX.cpp.s

src/communication/RS485.o: src/communication/RS485.cpp.o
.PHONY : src/communication/RS485.o

# target to build an object file
src/communication/RS485.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/communication/RS485.cpp.o
.PHONY : src/communication/RS485.cpp.o

src/communication/RS485.i: src/communication/RS485.cpp.i
.PHONY : src/communication/RS485.i

# target to preprocess a source file
src/communication/RS485.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/communication/RS485.cpp.i
.PHONY : src/communication/RS485.cpp.i

src/communication/RS485.s: src/communication/RS485.cpp.s
.PHONY : src/communication/RS485.s

# target to generate assembly for a file
src/communication/RS485.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/communication/RS485.cpp.s
.PHONY : src/communication/RS485.cpp.s

src/communication/client.o: src/communication/client.cpp.o
.PHONY : src/communication/client.o

# target to build an object file
src/communication/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/communication/client.cpp.o
.PHONY : src/communication/client.cpp.o

src/communication/client.i: src/communication/client.cpp.i
.PHONY : src/communication/client.i

# target to preprocess a source file
src/communication/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/communication/client.cpp.i
.PHONY : src/communication/client.cpp.i

src/communication/client.s: src/communication/client.cpp.s
.PHONY : src/communication/client.s

# target to generate assembly for a file
src/communication/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/communication/client.cpp.s
.PHONY : src/communication/client.cpp.s

src/filter/TrajectoryKF.o: src/filter/TrajectoryKF.cpp.o
.PHONY : src/filter/TrajectoryKF.o

# target to build an object file
src/filter/TrajectoryKF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/filter/TrajectoryKF.cpp.o
.PHONY : src/filter/TrajectoryKF.cpp.o

src/filter/TrajectoryKF.i: src/filter/TrajectoryKF.cpp.i
.PHONY : src/filter/TrajectoryKF.i

# target to preprocess a source file
src/filter/TrajectoryKF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/filter/TrajectoryKF.cpp.i
.PHONY : src/filter/TrajectoryKF.cpp.i

src/filter/TrajectoryKF.s: src/filter/TrajectoryKF.cpp.s
.PHONY : src/filter/TrajectoryKF.s

# target to generate assembly for a file
src/filter/TrajectoryKF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/filter/TrajectoryKF.cpp.s
.PHONY : src/filter/TrajectoryKF.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/preprocess/preprocess.o: src/preprocess/preprocess.cpp.o
.PHONY : src/preprocess/preprocess.o

# target to build an object file
src/preprocess/preprocess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/preprocess/preprocess.cpp.o
.PHONY : src/preprocess/preprocess.cpp.o

src/preprocess/preprocess.i: src/preprocess/preprocess.cpp.i
.PHONY : src/preprocess/preprocess.i

# target to preprocess a source file
src/preprocess/preprocess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/preprocess/preprocess.cpp.i
.PHONY : src/preprocess/preprocess.cpp.i

src/preprocess/preprocess.s: src/preprocess/preprocess.cpp.s
.PHONY : src/preprocess/preprocess.s

# target to generate assembly for a file
src/preprocess/preprocess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/preprocess/preprocess.cpp.s
.PHONY : src/preprocess/preprocess.cpp.s

src/preprocess/preprocess.o: src/preprocess/preprocess.cu.o
.PHONY : src/preprocess/preprocess.o

# target to build an object file
src/preprocess/preprocess.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/preprocess/preprocess.cu.o
.PHONY : src/preprocess/preprocess.cu.o

src/preprocess/preprocess.i: src/preprocess/preprocess.cu.i
.PHONY : src/preprocess/preprocess.i

# target to preprocess a source file
src/preprocess/preprocess.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/preprocess/preprocess.cu.i
.PHONY : src/preprocess/preprocess.cu.i

src/preprocess/preprocess.s: src/preprocess/preprocess.cu.s
.PHONY : src/preprocess/preprocess.s

# target to generate assembly for a file
src/preprocess/preprocess.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/preprocess/preprocess.cu.s
.PHONY : src/preprocess/preprocess.cu.s

src/prj_detector.o: src/prj_detector.cpp.o
.PHONY : src/prj_detector.o

# target to build an object file
src/prj_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/prj_detector.cpp.o
.PHONY : src/prj_detector.cpp.o

src/prj_detector.i: src/prj_detector.cpp.i
.PHONY : src/prj_detector.i

# target to preprocess a source file
src/prj_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/prj_detector.cpp.i
.PHONY : src/prj_detector.cpp.i

src/prj_detector.s: src/prj_detector.cpp.s
.PHONY : src/prj_detector.s

# target to generate assembly for a file
src/prj_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/prj_detector.cpp.s
.PHONY : src/prj_detector.cpp.s

src/time/time.o: src/time/time.cpp.o
.PHONY : src/time/time.o

# target to build an object file
src/time/time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/time/time.cpp.o
.PHONY : src/time/time.cpp.o

src/time/time.i: src/time/time.cpp.i
.PHONY : src/time/time.i

# target to preprocess a source file
src/time/time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/time/time.cpp.i
.PHONY : src/time/time.cpp.i

src/time/time.s: src/time/time.cpp.s
.PHONY : src/time/time.s

# target to generate assembly for a file
src/time/time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/time/time.cpp.s
.PHONY : src/time/time.cpp.s

src/worker/worker.o: src/worker/worker.cpp.o
.PHONY : src/worker/worker.o

# target to build an object file
src/worker/worker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/worker/worker.cpp.o
.PHONY : src/worker/worker.cpp.o

src/worker/worker.i: src/worker/worker.cpp.i
.PHONY : src/worker/worker.i

# target to preprocess a source file
src/worker/worker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/worker/worker.cpp.i
.PHONY : src/worker/worker.cpp.i

src/worker/worker.s: src/worker/worker.cpp.s
.PHONY : src/worker/worker.s

# target to generate assembly for a file
src/worker/worker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/worker/worker.cpp.s
.PHONY : src/worker/worker.cpp.s

src/yolov8_classifier/classifier.o: src/yolov8_classifier/classifier.cpp.o
.PHONY : src/yolov8_classifier/classifier.o

# target to build an object file
src/yolov8_classifier/classifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov8_classifier/classifier.cpp.o
.PHONY : src/yolov8_classifier/classifier.cpp.o

src/yolov8_classifier/classifier.i: src/yolov8_classifier/classifier.cpp.i
.PHONY : src/yolov8_classifier/classifier.i

# target to preprocess a source file
src/yolov8_classifier/classifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov8_classifier/classifier.cpp.i
.PHONY : src/yolov8_classifier/classifier.cpp.i

src/yolov8_classifier/classifier.s: src/yolov8_classifier/classifier.cpp.s
.PHONY : src/yolov8_classifier/classifier.s

# target to generate assembly for a file
src/yolov8_classifier/classifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov8_classifier/classifier.cpp.s
.PHONY : src/yolov8_classifier/classifier.cpp.s

src/yolov8_detector/detector.o: src/yolov8_detector/detector.cpp.o
.PHONY : src/yolov8_detector/detector.o

# target to build an object file
src/yolov8_detector/detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov8_detector/detector.cpp.o
.PHONY : src/yolov8_detector/detector.cpp.o

src/yolov8_detector/detector.i: src/yolov8_detector/detector.cpp.i
.PHONY : src/yolov8_detector/detector.i

# target to preprocess a source file
src/yolov8_detector/detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov8_detector/detector.cpp.i
.PHONY : src/yolov8_detector/detector.cpp.i

src/yolov8_detector/detector.s: src/yolov8_detector/detector.cpp.s
.PHONY : src/yolov8_detector/detector.s

# target to generate assembly for a file
src/yolov8_detector/detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov8_detector/detector.cpp.s
.PHONY : src/yolov8_detector/detector.cpp.s

src/yolov_pose/pose.o: src/yolov_pose/pose.cpp.o
.PHONY : src/yolov_pose/pose.o

# target to build an object file
src/yolov_pose/pose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov_pose/pose.cpp.o
.PHONY : src/yolov_pose/pose.cpp.o

src/yolov_pose/pose.i: src/yolov_pose/pose.cpp.i
.PHONY : src/yolov_pose/pose.i

# target to preprocess a source file
src/yolov_pose/pose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov_pose/pose.cpp.i
.PHONY : src/yolov_pose/pose.cpp.i

src/yolov_pose/pose.s: src/yolov_pose/pose.cpp.s
.PHONY : src/yolov_pose/pose.s

# target to generate assembly for a file
src/yolov_pose/pose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov_pose/pose.cpp.s
.PHONY : src/yolov_pose/pose.cpp.s

src/yolov_pose/yolo_pose_decode.o: src/yolov_pose/yolo_pose_decode.cu.o
.PHONY : src/yolov_pose/yolo_pose_decode.o

# target to build an object file
src/yolov_pose/yolo_pose_decode.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov_pose/yolo_pose_decode.cu.o
.PHONY : src/yolov_pose/yolo_pose_decode.cu.o

src/yolov_pose/yolo_pose_decode.i: src/yolov_pose/yolo_pose_decode.cu.i
.PHONY : src/yolov_pose/yolo_pose_decode.i

# target to preprocess a source file
src/yolov_pose/yolo_pose_decode.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov_pose/yolo_pose_decode.cu.i
.PHONY : src/yolov_pose/yolo_pose_decode.cu.i

src/yolov_pose/yolo_pose_decode.s: src/yolov_pose/yolo_pose_decode.cu.s
.PHONY : src/yolov_pose/yolo_pose_decode.s

# target to generate assembly for a file
src/yolov_pose/yolo_pose_decode.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trt.dir/build.make CMakeFiles/trt.dir/src/yolov_pose/yolo_pose_decode.cu.s
.PHONY : src/yolov_pose/yolo_pose_decode.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... trt"
	@echo "... src/TensorRT/calibrator/calibrator.o"
	@echo "... src/TensorRT/calibrator/calibrator.i"
	@echo "... src/TensorRT/calibrator/calibrator.s"
	@echo "... src/TensorRT/logger/logger.o"
	@echo "... src/TensorRT/logger/logger.i"
	@echo "... src/TensorRT/logger/logger.s"
	@echo "... src/TensorRT/model/model.o"
	@echo "... src/TensorRT/model/model.i"
	@echo "... src/TensorRT/model/model.s"
	@echo "... src/TensorRT/utils/utils.o"
	@echo "... src/TensorRT/utils/utils.i"
	@echo "... src/TensorRT/utils/utils.s"
	@echo "... src/ZEDX/ZEDX.o"
	@echo "... src/ZEDX/ZEDX.i"
	@echo "... src/ZEDX/ZEDX.s"
	@echo "... src/communication/RS485.o"
	@echo "... src/communication/RS485.i"
	@echo "... src/communication/RS485.s"
	@echo "... src/communication/client.o"
	@echo "... src/communication/client.i"
	@echo "... src/communication/client.s"
	@echo "... src/filter/TrajectoryKF.o"
	@echo "... src/filter/TrajectoryKF.i"
	@echo "... src/filter/TrajectoryKF.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/preprocess/preprocess.o"
	@echo "... src/preprocess/preprocess.i"
	@echo "... src/preprocess/preprocess.s"
	@echo "... src/preprocess/preprocess.o"
	@echo "... src/preprocess/preprocess.i"
	@echo "... src/preprocess/preprocess.s"
	@echo "... src/prj_detector.o"
	@echo "... src/prj_detector.i"
	@echo "... src/prj_detector.s"
	@echo "... src/time/time.o"
	@echo "... src/time/time.i"
	@echo "... src/time/time.s"
	@echo "... src/worker/worker.o"
	@echo "... src/worker/worker.i"
	@echo "... src/worker/worker.s"
	@echo "... src/yolov8_classifier/classifier.o"
	@echo "... src/yolov8_classifier/classifier.i"
	@echo "... src/yolov8_classifier/classifier.s"
	@echo "... src/yolov8_detector/detector.o"
	@echo "... src/yolov8_detector/detector.i"
	@echo "... src/yolov8_detector/detector.s"
	@echo "... src/yolov_pose/pose.o"
	@echo "... src/yolov_pose/pose.i"
	@echo "... src/yolov_pose/pose.s"
	@echo "... src/yolov_pose/yolo_pose_decode.o"
	@echo "... src/yolov_pose/yolo_pose_decode.i"
	@echo "... src/yolov_pose/yolo_pose_decode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

